# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    config.vm.define "debian_jessie" do |node|
        node.vm.box = "debian-jessie-qemu"
        # Allocate even more RAM and CPU if possible
        node.vm.provider :libvirt do |libvirt|
            libvirt.memory = 4096
            libvirt.cpus = 2
            libvirt.cpu_mode = 'host-passthrough'
    
            libvirt.uri = 'qemu+unix:///system'
            libvirt.driver = "kvm"
            libvirt.storage_pool_name = "default"
        end

        ## Share the default `vagrant` folder
        node.vm.synced_folder ".", "/vagrant", type: :nfs

        # Run the provisioning script
        node.vm.provision :shell, path: "../scripts/update-apt-proxy.sh"
    end
    

end

